### ISSUE TITLE
Environmental construction problems

### ISSUE THREAD

**Issue by Zhangfengmo** [montrealrobotics/ctrl-sim#2]
I am a beginner in machine learning, my tutor asked me to do some research on ctrl-sim. Is there any environment and tutorial?

**Comment by RLuke22** [comment]
Hello,

Upon acceptance of the paper, we will release the code, which includes a README to help reproduce the experiments in the main paper. Thanks for your patience.

**Comment by Zhangfengmo** [comment]
> Hello,
> 
> Upon acceptance of the paper, we will release the code, which includes a README to help reproduce the experiments in the main paper. Thanks for your patience.

Hello,

I am glad to receive your reply. May I ask if my implementation approach is generally the same?

Parse the JSON folder of the relevant initial datasets (Train and Valid) and input them into the Nocturne integrated Box2D simulator.
Extract the data processed by the simulator, and then use Transformer and offRL for corresponding training.
After completing the training, generate the corresponding simulation videos through Nocturne.
Thank you.

Best regards,

FengmoZhang

**Comment by RLuke22** [comment]
Yes, this approach is correct.
