### ISSUE TITLE
Inquiry about Pretraining Dataset Construction Using Waymo Motion Dataset

### ISSUE THREAD

**Issue by Zhangfengmo** [montrealrobotics/ctrl-sim#3]
Dear Luke Rowe,

I hope this email finds you well.

I am pleased to see that your paper has been accepted and that the related code has been made open-source. I am currently working on reconstructing a pretraining dataset based on the data in the scenario folder of the Waymo Motion dataset. To assist with this, I have included images showcasing the contents of the folder for better clarity.

Could you kindly share your approach or any insights on how you processed the data? Any guidance you can provide would be greatly appreciated.

Looking forward to hearing from you. Thank you for your time and assistance!

Best regards,
fengmozhang

![image](https://github.com/user-attachments/assets/e8858c8e-a1e2-4732-90be-51585566d408)
![image](https://github.com/user-attachments/assets/28050781-bf95-4639-922a-3f3b39933776)

**Comment by RLuke22** [comment]
Hi Fengmo,

Sorry for the late reply. We work directly with the nocturne-processed waymo data. The code to convert the raw waymo data (as shown in your attached image) to a nocturne-compatible format can be found here: https://github.com/facebookresearch/nocturne/tree/main/scripts/json_generation
